from django.urls import path
from .views import SAP_APO_comparison, plant_view, machine_view, partno_view, show_smartkpiorderkeyvaluedata, show_smartkpimachinemessagedata, show_smartkpi, mass_ofset, get_tgmax, get_apo, get_tgmax_group, get_oee, get_oee_ajax, show_production_advisor, ajax_parts_to_production_advisor, ajax_target_delta, excel_api_order_info, production_file, operators_on_line, shift_screen, get_shift_calendar, get_production_plan_time, shift_factor, cm_designer, prepare_data_operators, cm_visualizer, get_plc_tag_value, prepare_data_operators_beta, charts, prepare_data_master, prepare_data_production_beta, prepare_data_box_plot, statistical_data, charts_all, dlp1_screen, dlp1_screen_operator, local_infrastructure, ping_meskit, fp09_stats, fp09_alarm_descriptions, fp09_data, fp09_oee, fp09_oee_data, fp09_oee_manual_entries, ping_meskit, reboot_meskit, restart_meskit, get_parts_count, dlp1_graph_test, times_comparison, calculation_dlp1, card_reader

urlpatterns = [
    path('thingworx/plant_view', plant_view, name='plant_view'),
    path('thingworx/machine_view', machine_view, name='machine_view'),
    path('thingworx/partno_view', partno_view, name='partno_view'),
    path('thingworx/show_smartkpiorderkeyvaluedata', show_smartkpiorderkeyvaluedata, name='show_smartkpiorderkeyvaluedata'),
    path('thingworx/show_smartkpimachinemessagedata', show_smartkpimachinemessagedata, name='show_smartkpimachinemessagedata'),
    path('thingworx/show_smartkpi', show_smartkpi, name='show_smartkpi'),
    path('thingworx/mass_ofset', mass_ofset, name='mass_ofset'),
    path('thingworx/get_tgmax', get_tgmax, name='get_tgmax'),
    path('thingworx/get_tgmax_group', get_tgmax_group, name='get_tgmax_group'),
    path('thingworx/get_apo', get_apo, name='get_apo'),
    path('thingworx/get_oee', get_oee, name='get_oee'),
    path('thingworx/production_advisor', show_production_advisor, name='show_production_advisor'),
    path('thingworx/get_oee_ajax', get_oee_ajax, name='get_oee_ajax'),
    path('thingworx/excel_api_order_info', excel_api_order_info, name='excel_api_order_info'),
    path('thingworx/ajax_parts_to_production_advisor', ajax_parts_to_production_advisor, name='ajax_parts_to_production_advisor'),
    path('thingworx/ajax_target_delta', ajax_target_delta, name='ajax_target_delta'),
    path('thingworx/production_file', production_file, name='production_file'),
    path('thingworx/operators_on_line', operators_on_line, name='operators_on_line'),
    path('thingworx/shift_screen', shift_screen, name='shift_screen'),
    path('thingworx/get_shift_calendar', get_shift_calendar, name='get_shift_calendar'),
    path('thingworx/get_production_plan_time', get_production_plan_time, name='get_production_plan_time'),
    path('thingworx/shift_factor', shift_factor, name='shift_factor'),
    path('thingworx/prepare_data_operators', prepare_data_operators, name='prepare_data_operators'),
    path('thingworx/prepare_data_operators_beta', prepare_data_operators_beta, name='prepare_data_operators_beta'),
    path('thingworx/prepare_data_master', prepare_data_master, name='prepare_data_master'),
    path('thingworx/prepare_data_production_beta', prepare_data_production_beta, name='prepare_data_production_beta'),
    path('thingworx/prepare_data_box_plot', prepare_data_box_plot, name='prepare_data_box_plot'),
    path('thingworx/statistical_data', statistical_data, name='statistical_data'),
    path('cm/cm_designer', cm_designer, name='cm_designer'),
    path('cm/get_plc_tag_value/<str:plc_tag>', get_plc_tag_value, name='get_plc_tag_value'),
    path('cm/<str:canvas>', cm_visualizer, name='cm_visualizer'),
    path('thingworx/charts', charts, name='charts'),
    path('thingworx/charts_all', charts_all, name='charts_all'),
    path('thingworx/dlp1', dlp1_screen, name='dlp1_screen'),
    path('thingworx/dlp1_graph_test', dlp1_graph_test, name='dlp1_graph_test'),
    path('thingworx/dlp1_operator', dlp1_screen_operator, name='dlp1_screen_operator'),
    path('thingworx/times_comparison', times_comparison, name='times_comparison'),
    path('thingworx/calculation_dlp1', calculation_dlp1, name='calculation_dlp1'),
    path('thingworx/local_infrastructure', local_infrastructure, name='local_infrastructure'),
    path('thingworx/local_infrastructure/ping_meskit', ping_meskit, name='ping_meskit'),
    path('thingworx/fp09_stats', fp09_stats, name='fp09_stats'),
    path('thingworx/fp09_alarm_descriptions', fp09_alarm_descriptions, name='fp09_alarm_descriptions'),
    path('thingworx/fp09_data', fp09_data, name='fp09_data'),
    path('thingworx/fp09_oee', fp09_oee, name='fp09_oee'),
    path('thingworx/fp09/get_parts_count', get_parts_count, name='get_parts_count'),
    path('thingworx/fp09_oee_data', fp09_oee_data, name='fp09_oee_data'),
    path('thingworx/fp09_oee_manual_entries', fp09_oee_manual_entries, name='fp09_oee_manual_entries'),
    path('thingworx/local_infrastructure/reboot_meskit', reboot_meskit, name='reboot_meskit'),
    path('thingworx/local_infrastructure/restart_meskit', restart_meskit, name='restart_meskit'),
    path('thingworx/sap_apo_comparison', SAP_APO_comparison, name='SAP_APO_comparison'),
    path('thingworx/cards', card_reader, name='card_reader')
]

